"use client";
import Link from "next/link";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { BrandLockup } from "@/components/app/brand";

export default function SignupPage(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage("");const supabase=createClient();const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/auth/confirm?next=/app`}});setMessage(error?error.message:"Check your email to confirm your account, then sign in.");setLoading(false);}return <main className="grid min-h-screen place-items-center px-6"><div className="w-full max-w-sm"><Link href="/" className="mb-10 inline-flex text-sm font-semibold"><BrandLockup priority /></Link><h1 className="text-2xl font-semibold">Create your workspace</h1><p className="mt-2 text-sm text-muted-foreground">Your private assistants, documents and conversations.</p><form className="mt-7 space-y-4" onSubmit={submit}><div><label className="mb-1.5 block text-xs text-muted-foreground">Email</label><Input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div><label className="mb-1.5 block text-xs text-muted-foreground">Password</label><Input type="password" required minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/><p className="mt-1 text-[11px] text-muted-foreground">At least 8 characters. Configure stronger password rules in Supabase Auth for production.</p></div>{message&&<p className="text-sm text-zinc-300">{message}</p>}<Button className="w-full" disabled={loading}>{loading?"Creating…":"Create account"}</Button></form><p className="mt-5 text-center text-sm text-muted-foreground">Already have an account? <Link className="text-foreground underline underline-offset-4" href="/login">Sign in</Link></p></div></main>}
