import { headers } from "next/headers";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export default async function SettingsPage(){
  const {supabase,userId,claims}=await requireUser();
  const [{data:profile},requestHeaders]=await Promise.all([supabase.from("profiles").select("display_name,default_country,default_region").eq("id",userId).maybeSingle(),headers()]);
  const ipCountry=requestHeaders.get("x-vercel-ip-country");const ipRegion=requestHeaders.get("x-vercel-ip-country-region");
  let countrySuggestion=ipCountry||"";try{if(ipCountry)countrySuggestion=new Intl.DisplayNames(["en"],{type:"region"}).of(ipCountry)||ipCountry}catch{}
  async function save(formData:FormData){"use server";const{supabase,userId}=await requireUser();await supabase.from("profiles").update({display_name:String(formData.get("displayName")||"").slice(0,120)||null,default_country:String(formData.get("country")||"").slice(0,80)||null,default_region:String(formData.get("region")||"").slice(0,100)||null,updated_at:new Date().toISOString()}).eq("id",userId);revalidatePath("/app/settings");}
  return <div className="max-w-2xl"><p className="text-xs uppercase tracking-[.18em] text-muted-foreground">Workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Settings</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Your saved jurisdiction is only a default for new specialist assistants. Legal and tax jurisdiction can always be overridden per assistant.</p><form action={save}><Card className="mt-7 space-y-5 p-6"><label className="block text-xs text-muted-foreground">Display name<Input name="displayName" className="mt-2" defaultValue={profile?.display_name||""}/></label><label className="block text-xs text-muted-foreground">Email<Input className="mt-2" value={String(claims.email||"")} disabled/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs text-muted-foreground">Default country / jurisdiction<Input name="country" className="mt-2" defaultValue={profile?.default_country||countrySuggestion}/></label><label className="block text-xs text-muted-foreground">Default state / region<Input name="region" className="mt-2" defaultValue={profile?.default_region||ipRegion||""}/></label></div>{!profile?.default_country&&ipCountry?<div className="rounded-lg border bg-muted/30 p-3 text-xs leading-5 text-muted-foreground">Suggested from coarse request location: {countrySuggestion}{ipRegion?` / ${ipRegion}`:""}. This is not treated as legal or tax residency until you save/confirm it.</div>:null}<Button type="submit">Save settings</Button></Card></form><Card className="mt-4 p-5"><h2 className="text-sm font-medium">Privacy defaults</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Private uploads remain scoped to your workspace. Location is not stored unless you save it. Professional assistants should confirm matter-specific jurisdiction where it differs from your default.</p></Card></div>;
}
