"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import Papa from "papaparse";
import { AlertTriangle, Download, FileUp, Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { analyzePortfolio, type Exposure, type PortfolioPosition } from "@/lib/portfolio/analytics";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";

const empty:PortfolioPosition={symbol:"",name:"",value:0,sector:"",industry:"",assetClass:"Equity",region:"India",currency:"INR",account:""};
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
const money=(n:number,currency:string)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:currency||"INR",maximumFractionDigits:0}).format(n);

function ExposureRows({title,rows}:{title:string;rows:Exposure[]}){return <Card className="p-5"><h3 className="text-sm font-medium">{title}</h3><div className="mt-4 space-y-3">{rows.slice(0,8).map(row=><div key={row.label}><div className="mb-1 flex items-center justify-between text-xs"><span className="truncate text-muted-foreground">{row.label}</span><span>{pct(row.weight)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-zinc-300" style={{width:`${Math.max(1,row.weight*100)}%`}}/></div></div>)}</div></Card>}

export function PortfolioManager(){
  const [name,setName]=useState("My Portfolio");const [baseCurrency,setBaseCurrency]=useState("INR");const [positions,setPositions]=useState<PortfolioPosition[]>([]);const [saving,setSaving]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{fetch("/api/portfolio").then(r=>r.json()).then(data=>{if(data.portfolio){setName(data.portfolio.name);setBaseCurrency(data.portfolio.base_currency);setPositions(data.positions||[]);}}).catch(()=>undefined)},[]);
  const analytics=useMemo(()=>analyzePortfolio(positions),[positions]);
  function update(i:number,key:keyof PortfolioPosition,value:string|number){setPositions(rows=>rows.map((row,index)=>index===i?{...row,[key]:key==="value"?Number(value):value}:row));}
  function parseCsv(file:File){Papa.parse<Record<string,string>>(file,{header:true,skipEmptyLines:true,complete(result){const normalized=result.data.map(row=>({symbol:row.symbol||row.Symbol||row.ticker||row.Ticker||"",name:row.name||row.Name||row.company||row.Company||row.symbol||row.Symbol||"",value:Number(row.value||row.Value||row.current_value||row.market_value||row["Market Value"]||0),sector:row.sector||row.Sector||"",industry:row.industry||row.Industry||"",assetClass:row.asset_class||row.assetClass||row["Asset Class"]||"Equity",region:row.region||row.Region||"India",currency:row.currency||row.Currency||baseCurrency,account:row.account||row.Account||""})).filter(row=>row.name&&Number.isFinite(row.value)&&row.value>0);if(!normalized.length){toast.error("No valid rows found. Use the CSV template columns.");return}setPositions(normalized);toast.success(`Imported ${normalized.length} positions`);}})}
  async function save(){if(!analytics.positionCount){toast.error("Add at least one positive-value position.");return}setSaving(true);try{const res=await fetch("/api/portfolio",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,baseCurrency,positions})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Save failed");toast.success("Portfolio saved. Your Portfolio Manager assistant can now analyze it.");}catch(e){toast.error(e instanceof Error?e.message:"Save failed")}finally{setSaving(false)}}
  return <div className="space-y-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-muted-foreground">Portfolio Manager</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Exposure and diversification</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Analyze current allocation, concentration and diversification. This assistant deliberately does not forecast prices, select options trades or provide market-timing predictions.</p></div><div className="flex gap-2"><input ref={inputRef} className="hidden" type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)parseCsv(f);e.currentTarget.value=""}}/><Button variant="secondary" onClick={()=>inputRef.current?.click()}><FileUp className="size-4"/>Import CSV</Button><a href="/portfolio-template.csv" download><Button variant="secondary"><Download className="size-4"/>Template</Button></a><Button onClick={save} disabled={saving}><Save className="size-4"/>{saving?"Saving...":"Save"}</Button></div></div>

  <Card className="p-5"><div className="grid gap-4 sm:grid-cols-3"><label className="text-xs text-muted-foreground">Portfolio name<Input className="mt-2" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-xs text-muted-foreground">Base currency<Input className="mt-2" value={baseCurrency} maxLength={8} onChange={e=>setBaseCurrency(e.target.value.toUpperCase())}/></label><div className="flex items-end"><Link href="/app/bots/new?preset=portfolio" className="w-full"><Button variant="secondary" className="w-full">Create Portfolio Manager assistant</Button></Link></div></div></Card>

  {analytics.positionCount>0&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card className="p-4"><div className="text-xs text-muted-foreground">Portfolio value</div><div className="mt-2 text-xl font-semibold">{money(analytics.totalValue,baseCurrency)}</div></Card><Card className="p-4"><div className="text-xs text-muted-foreground">Unique securities</div><div className="mt-2 text-xl font-semibold">{analytics.positionCount}</div><div className="mt-1 text-[11px] text-muted-foreground">{analytics.lineItemCount} line items</div></Card><Card className="p-4"><div className="text-xs text-muted-foreground">Largest position</div><div className="mt-2 text-xl font-semibold">{pct(analytics.top1Weight)}</div></Card><Card className="p-4"><div className="text-xs text-muted-foreground">Top 3</div><div className="mt-2 text-xl font-semibold">{pct(analytics.top3Weight)}</div></Card><Card className="p-4"><div className="text-xs text-muted-foreground">Effective holdings</div><div className="mt-2 text-xl font-semibold">{analytics.effectiveHoldings.toFixed(1)}</div><div className="mt-1 text-[11px] text-muted-foreground">1 / HHI</div></Card></div>
  {analytics.alerts.length>0&&<Card className="border-amber-900/50 bg-amber-950/10 p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-amber-400"/><div><h3 className="text-sm font-medium">Concentration flags</h3><ul className="mt-2 space-y-1 text-sm text-muted-foreground">{analytics.alerts.map(a=><li key={a}>• {a}</li>)}</ul></div></div></Card>}
  <div className="grid gap-3 lg:grid-cols-2"><ExposureRows title="Sector exposure" rows={analytics.sectorExposure}/><ExposureRows title="Industry exposure" rows={analytics.industryExposure}/><ExposureRows title="Asset-class exposure" rows={analytics.assetClassExposure}/><ExposureRows title="Region exposure" rows={analytics.regionExposure}/><ExposureRows title="Currency exposure" rows={analytics.currencyExposure}/><ExposureRows title="Account exposure" rows={analytics.accountExposure}/></div></>}

  <Card className="overflow-hidden"><div className="flex items-center justify-between border-b p-4"><div><h2 className="text-sm font-medium">Positions</h2><p className="mt-1 text-xs text-muted-foreground">Use current market value for each holding. Classification fields drive exposure analytics.</p></div><Button size="sm" variant="secondary" onClick={()=>setPositions(p=>[...p,{...empty,currency:baseCurrency}])}><Plus className="size-4"/>Add</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-xs"><thead className="bg-muted/40 text-muted-foreground"><tr>{["Symbol","Name","Value","Sector","Industry","Asset class","Region","Currency","Account",""] .map(h=><th key={h} className="px-3 py-2 font-medium">{h}</th>)}</tr></thead><tbody>{positions.map((p,i)=><tr key={i} className="border-t"><td className="p-2"><Input value={p.symbol||""} onChange={e=>update(i,"symbol",e.target.value)}/></td><td className="p-2"><Input value={p.name} onChange={e=>update(i,"name",e.target.value)}/></td><td className="p-2"><Input type="number" min="0" step="0.01" value={p.value||""} onChange={e=>update(i,"value",e.target.value)}/></td><td className="p-2"><Input value={p.sector||""} onChange={e=>update(i,"sector",e.target.value)}/></td><td className="p-2"><Input value={p.industry||""} onChange={e=>update(i,"industry",e.target.value)}/></td><td className="p-2"><Input value={p.assetClass||""} onChange={e=>update(i,"assetClass",e.target.value)}/></td><td className="p-2"><Input value={p.region||""} onChange={e=>update(i,"region",e.target.value)}/></td><td className="p-2"><Input value={p.currency||""} onChange={e=>update(i,"currency",e.target.value)}/></td><td className="p-2"><Input value={p.account||""} onChange={e=>update(i,"account",e.target.value)}/></td><td className="p-2"><button aria-label={`Delete ${p.name||p.symbol||"position"}`} onClick={()=>setPositions(rows=>rows.filter((_,index)=>index!==i))} className="grid size-8 place-items-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground"><Trash2 className="size-4"/></button></td></tr>)}{!positions.length&&<tr><td colSpan={10} className="p-8 text-center text-muted-foreground">Import a CSV or add your first position.</td></tr>}</tbody></table></div></Card>

  {analytics.weights.length>0&&<Card className="p-5"><div className="flex items-center gap-2"><h2 className="text-sm font-medium">Position weights</h2><Badge>deterministic</Badge></div><div className="mt-4 space-y-3">{analytics.weights.slice(0,20).map(p=><div key={`${p.symbol}-${p.name}`} className="grid grid-cols-[minmax(120px,1fr)_minmax(100px,2fr)_64px] items-center gap-3"><div className="truncate text-xs">{p.symbol||p.name}</div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-zinc-300" style={{width:`${Math.max(1,p.weight*100)}%`}}/></div><div className="text-right text-xs text-muted-foreground">{pct(p.weight)}</div></div>)}</div></Card>}
  </div>;
}
